import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import { Image, Box, Text, Center, Divider, Wrap, WrapItem, Select, InputGroup, InputRightElement, Input, Stack, IconButton, Heading, Button, background, UnorderedList, ListItem } from '@chakra-ui/react'
import { GiStonePath } from 'react-icons/gi';
import { SiAirtable } from 'react-icons/si'
import BodyBanner from '@/components/BodyBanner'
import PreTitle from '@/components/PreTitle'
import { BsArrowRight, BsRulers } from 'react-icons/bs'
import { motion } from 'framer-motion';
import IconMove from '@/components/IconMove'
const inter = Inter({ subsets: ['latin'] })
import { useInView } from "react-intersection-observer";
import { GetStaticProps } from 'next'
import SliderImages from '@/components/SliderImages'
import SliderImagesTo from '@/components/SliderImagesTo'
import SliderTestemonials from '@/components/SliderTestemonials'

export default function Home() {
  const [ref, inView] = useInView({
    triggerOnce: true,
    threshold: 0.1,
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BodyBanner />
      <Center flexDir={'column'}>
        <Box w='95%' marginLeft={{ base: '2%', md: '2%', lg: '4%' }} justifyContent={'flex-start'}   >
          <PreTitle colorTitle={undefined} base='20%' md='20%' lg='13%' text='O QUE NÓS OFERECEMOS' title='Oferecemos Os Melhores Serviços' />
          <Divider marginTop={'3%'} h='0.08em' bg='gray.300' orientation='horizontal' />
        </Box>
        <Box marginTop='1%' w='95%' marginLeft={{ base: '2%', md: '2%', lg: '4%' }} justifyContent={'flex-start'}   >
        <motion.div
        ref={ref}
        
        animate={inView ? { x: 0 } : {}}
        transition={{ duration: 0.8 }}
      >
          <Wrap spacing='40px'>

            <WrapItem w={{ base: 'full', md: '30%' }}>
              
                <Box w='full' bg='white' flexDir='column'>
                  <Box marginLeft='50px'>
                    <IconMove iconLeft={<SiAirtable color="#30373F" size="70px" />} iconRigth={<SiAirtable color="#E4E4E6" size="70px" />} />
                  </Box>
                  <Box margin='40px 40px 40px 40px' justifyContent={'flex-start'} >
                    <Heading fontWeight={'500'} size={{ base: 'lg', md: 'lg', lg: 'xl' }} color='black'>
                      Bancadas
                    </Heading>
                    <Text marginTop='15px' fontWeight={'400'}>
                      Fabricar e instalar bancadas de cozinha, banheiro e áreas de serviço feitas de mármore ou granito.
                    </Text>
                  </Box>
                  <Center>
                    <Divider w='85%' marginTop={'3%'} h='0.1em' bg='gray.400' orientation='horizontal' />
                  </Center>
                  <motion.div
                    whileHover={{ rotateX: 360 }}
                    transition={{ duration: 1 }}
                    style={{ display: 'inline-block' }}
                  >
                    <IconButton
                      marginTop='20px'
                      marginLeft='30px'
                      bg='transparent'
                      _hover={{ bg: 'transparent' }}
                      aria-label='Search database'
                      icon={<BsArrowRight color="var(--primary)" size='40px' />}
                    />
                  </motion.div>
                </Box>
            </WrapItem>


            <WrapItem w={{ base: 'full', md: '30%' }}>
              
                <Box w='full' bg='white' flexDir='column'>
                  <Box marginLeft='50px'>
                    <IconMove iconLeft={<GiStonePath color="#30373F" size="70px" />} iconRigth={<GiStonePath color="#E4E4E6" size="70px" />} />
                  </Box>
                  <Box margin='40px 40px 40px 40px' justifyContent={'flex-start'} >
                    <Heading fontWeight={'500'} size={{ base: 'lg', md: 'lg', lg: 'xl' }} color='black'>
                      Revestimento
                    </Heading>
                    <Text marginTop='15px' fontWeight={'400'}>
                      De pisos e paredes. Isso envolve a escolha do tipo de pedra, corte e acabamento preferências.
                    </Text>
                  </Box>
                  <Center>
                    <Divider w='85%' marginTop={'3%'} h='0.1em' bg='gray.400' orientation='horizontal' />
                  </Center>
                  <motion.div
                    whileHover={{ rotateX: 360 }}
                    transition={{ duration: 1 }}
                    style={{ display: 'inline-block' }}
                  >
                    <IconButton
                      marginTop='20px'
                      marginLeft='30px'
                      bg='transparent'
                      _hover={{ bg: 'transparent' }}
                      aria-label='Search database'
                      icon={<BsArrowRight color="var(--primary)" size='40px' />}
                    />
                  </motion.div>
                </Box>
          
            </WrapItem>

            <WrapItem w={{ base: 'full', md: '30%' }}>
            
                <Box w='full' bg='white' flexDir='column'>
                  <Box marginLeft='50px'>
                    <IconMove iconLeft={<BsRulers color="#30373F" size="70px" />} iconRigth={<BsRulers color="#E4E4E6" size="70px" />} />
                  </Box>
                  <Box margin='40px 40px 40px 40px' justifyContent={'flex-start'} >
                    <Heading fontWeight={'500'} size={{ base: 'lg', md: 'lg', lg: 'xl' }} color='black'>
                      Sob Medida
                    </Heading>
                    <Text marginTop='15px' fontWeight={'400'}>
                      Produzir peças sob medida, como soleiras, peitoris de janela, escadas, lareiras, mesas e muito mais.
                    </Text>
                  </Box>
                  <Center>
                    <Divider w='85%' marginTop={'3%'} h='0.1em' bg='gray.400' orientation='horizontal' />
                  </Center>
                  <motion.div
                    whileHover={{ rotateX: 360 }}
                    transition={{ duration: 1 }}
                    style={{ display: 'inline-block' }}
                  >
                    <IconButton
                      marginTop='20px'
                      marginLeft='30px'
                      bg='transparent'
                      _hover={{ bg: 'transparent' }}
                      aria-label='Search database'
                      icon={<BsArrowRight color="var(--primary)" size='40px' />}
                    />
                  </motion.div>
                </Box>
            </WrapItem>


          </Wrap>
          </motion.div>
        </Box>



      </Center>
      <Center marginTop='10%' flexDir={{ base: 'column', md: 'column', lg: 'row' }} bg='white'>
        <Box w={{ base: '100%', md: '100%', lg: '70%' }}>
          <Image src='/pedra.jpg' alt='' width={'full'} height={'full'} />
        </Box>
        <Box marginLeft={'3%'} >
          <PreTitle colorTitle={undefined} base='20%' md='20%' lg='0%' text='SOBRE NÓS' title='Visite nosso Armazém de Mármore e Granito' />
          <Text marginTop='15px' fontWeight={'400'} >
            Na Margran, garantimos produtos de pedra de alta qualidade, como ladrilhos e lajes cuidadosamente selecionados de várias partes do mundo, para elevar o design da sua casa.
          </Text>
          <Divider margin={'4% 4% 4% 0%'} h='0.1em' bg='gray.400' orientation='horizontal' />

          <Center flexDir={'row'} justifyContent={'flex-start'} >
            <Box>
              <Heading fontWeight={'500'} size={{ base: 'md', md: 'md', lg: 'lg' }} color='var(--secondary)' marginBottom='5%'>
                Visão do mármore
              </Heading>
              <UnorderedList spacing={'5%'}>
                <ListItem color='var(--text-color)'>Mais caro</ListItem>
                <ListItem color='var(--text-color)'>Mármore Alicante Vermelho</ListItem>
                <ListItem color='var(--text-color)'>Menos manutenção</ListItem>
                <ListItem color='var(--text-color)'>Muito durável</ListItem>
              </UnorderedList>
            </Box>
            <Box marginLeft='5%'>
              <Heading fontWeight={'500'} size={{ base: 'md', md: 'md', lg: 'lg' }} color='var(--secondary)' marginBottom='5%'>
                Visão do granito
              </Heading>
              <UnorderedList spacing={'5%'}>
                <ListItem color='var(--text-color)' >Resistência ao calor</ListItem>
                <ListItem color='var(--text-color)' >Variedade de cores e padrões</ListItem>
                <ListItem color='var(--text-color)' >Resistência a manchas</ListItem>
                <ListItem color='var(--text-color)' >Durabilidade excepcional</ListItem>
              </UnorderedList>
            </Box>

          </Center>

        </Box>
      </Center>

      <Box
        w='full'
        justifyContent={'flex-start'}
        backgroundImage="/pedra2.jpg"
        backgroundSize="cover"
        backgroundRepeat="no-repeat"
        backgroundPosition="center"
        paddingBottom='10%'
        paddingTop='10%'
      >
        <Center w='full' >
          <Box margin='0px 0px  0px 5%' w='95%'>
            <PreTitle colorTitle='white' base='0%' md='0%' lg='0%' text='ESCOLHA SUA PEDRA' title='Showroom Com Seleção' />
            <Divider marginTop={'3%'} h='0.08em' bg='gray.300' orientation='horizontal' />
          </Box>

        </Center >

        <Center w='full' marginTop='5%'  >
          <SliderImages />
        </Center>
      </Box>
      <Box
        w='full'
        justifyContent={'flex-start'}
        backgroundColor='white'
        paddingBottom='5%'
        paddingTop='10%'
      >
        <Center w='full' >
          <Box margin='0px 0px  0px 5%' w='95%'>
            <PreTitle colorTitle={undefined} base='0%' md='0%' lg='0%' text='TRABALHO MAIS RECENTE' title='Conheça Nossa Criação' />
            <Divider marginTop={'3%'} h='0.08em' bg='gray.300' orientation='horizontal' />
          </Box>

        </Center >

        <Center w='full' marginTop='5%'  >
          <SliderImagesTo />
        </Center>
      </Box>

      <Center flexDir={'row'}  bg='#F6F4F5' alignItems={'flex-start'}>
        <Box w='60%' marginTop='5%' marginLeft={{ base: '2%', md: '2%', lg: '4%' }}    >
          <PreTitle colorTitle={'var(--secondary)'} base='20%' md='20%' lg='5%' text='NOSSOS MELHORES PRÊMIOS' title='Prêmios & Reconhecimentos' />
        </Box>
        <Box marginTop='5%' marginBottom={'5%'} w='full' marginLeft={{ base: '2%', md: '2%', lg: '4%' }} justifyContent={'flex-start'}   >
          <Wrap spacing='30px'>

            <WrapItem w={{ base: 'full', md: '45%' }}>
              <motion.div
                ref={ref}
                initial={{ y: 300 }}
                animate={inView ? { y: 0 } : {}}
                transition={{ duration: 0.5 }}
              >
                <Box w='full' bg='#F6F4F5' flexDir='column'>
                  <Box margin='40px 40px 40px 40px' justifyContent={'flex-start'} >
                    <Center justifyContent={'flex-start'}>
                      <Heading fontWeight={'500'} size={{ base: 'lg', md: 'lg', lg: 'xl' }} color='var(--primary)' marginRight='2%'>
                        01
                      </Heading> 
                      <Heading fontWeight={'500'} size={{ base: 'lg', md: 'lg', lg: 'xl' }} color='var(--secondary)'>
                      Prêmios 1
                      </Heading>
                    </Center>
                    <Center>
                      <Divider w='full' marginTop={'3%'} h='0.1em' bg='gray.400' orientation='horizontal' />
                    </Center>
                    <Text marginTop='15px' fontWeight={'400'} color='#616161'>
                    Este prêmio reconhece um fulano que teve uma nova ideia ou processo que teve um impacto positivo na empresa
                     </Text>
                  </Box>

                  <motion.div
                    whileHover={{ rotateX: 360 }}
                    transition={{ duration: 1 }}
                    style={{ display: 'inline-block' }}
                  >
                    <IconButton
                      marginTop='0px'
                      marginLeft='30px'
                      bg='transparent'
                      _hover={{ bg: 'transparent' }}
                      aria-label='Search database'
                      icon={<BsArrowRight color="var(--primary)" size='40px' />}
                    />
                  </motion.div>
                </Box>
              </motion.div>
            </WrapItem>


            <WrapItem w={{ base: 'full', md: '45%' }}>
              <motion.div
                ref={ref}
                initial={{ y: 300 }}
                animate={inView ? { y: 0 } : {}}
                transition={{ duration: 0.5 }}
              >
                <Box w='full' bg='#F6F4F5' flexDir='column'>
                <Box margin='40px 40px 40px 40px' justifyContent={'flex-start'} >
                    <Center justifyContent={'flex-start'}>
                      <Heading fontWeight={'500'} size={{ base: 'lg', md: 'lg', lg: 'xl' }} color='var(--primary)' marginRight='2%'>
                        02
                      </Heading> 
                      <Heading fontWeight={'500'} size={{ base: 'lg', md: 'lg', lg: 'xl' }} color='var(--secondary)'>
                      Prêmios 2
                      </Heading>
                    </Center>
                    <Center>
                      <Divider w='full' marginTop={'3%'} h='0.1em' bg='gray.400' orientation='horizontal' />
                    </Center>
                    <Text marginTop='15px' fontWeight={'400'} color='#616161'>
                    Este prêmio reconhece um fulano que teve uma nova ideia ou processo que teve um impacto positivo na empresa
                     </Text>
                  </Box>

                  <motion.div
                    whileHover={{ rotateX: 360 }}
                    transition={{ duration: 1 }}
                    style={{ display: 'inline-block' }}
                  >
                    <IconButton
                      marginTop='0px'
                      marginLeft='30px'
                      bg='transparent'
                      _hover={{ bg: 'transparent' }}
                      aria-label='Search database'
                      icon={<BsArrowRight color="var(--primary)" size='40px' />}
                    />
                  </motion.div>
                </Box>
              </motion.div>
            </WrapItem>

            <WrapItem w={{ base: 'full', md: '45%' }}>
              <motion.div
                ref={ref}
                initial={{ y: 300 }}
                animate={inView ? { y: 0 } : {}}
                transition={{ duration: 0.5 }}
              >
                <Box w='full' bg='#F6F4F5' flexDir='column'>
                <Box margin='40px 40px 40px 40px' justifyContent={'flex-start'} >
                    <Center justifyContent={'flex-start'}>
                      <Heading fontWeight={'500'} size={{ base: 'lg', md: 'lg', lg: 'xl' }} color='var(--primary)' marginRight='2%'>
                        03
                      </Heading> 
                      <Heading fontWeight={'500'} size={{ base: 'lg', md: 'lg', lg: 'xl' }} color='var(--secondary)'>
                      Prêmios 3
                      </Heading>
                    </Center>
                    <Center>
                      <Divider w='full' marginTop={'3%'} h='0.1em' bg='gray.400' orientation='horizontal' />
                    </Center>
                    <Text marginTop='15px' fontWeight={'400'} color='#616161'>
                    Este prêmio reconhece um fulano que teve uma nova ideia ou processo que teve um impacto positivo na empresa
                     </Text>
                  </Box>

                  <motion.div
                    whileHover={{ rotateX: 360 }}
                    transition={{ duration: 1 }}
                    style={{ display: 'inline-block' }}
                  >
                    <IconButton
                      marginTop='0px'
                      marginLeft='30px'
                      bg='transparent'
                      _hover={{ bg: 'transparent' }}
                      aria-label='Search database'
                      icon={<BsArrowRight color="var(--primary)" size='40px' />}
                    />
                  </motion.div>
                </Box>
              </motion.div>
            </WrapItem>
            <WrapItem w={{ base: 'full', md: '45%' }}>
              <motion.div
                ref={ref}
                initial={{ y: 300 }}
                animate={inView ? { y: 0 } : {}}
                transition={{ duration: 0.5 }}
              >
                <Box w='full' bg='#F6F4F5' flexDir='column'>
                <Box margin='40px 40px 40px 40px' justifyContent={'flex-start'} >
                    <Center justifyContent={'flex-start'}>
                      <Heading fontWeight={'500'} size={{ base: 'lg', md: 'lg', lg: 'xl' }} color='var(--primary)' marginRight='2%'>
                        04
                      </Heading> 
                      <Heading fontWeight={'500'} size={{ base: 'lg', md: 'lg', lg: 'xl' }} color='var(--secondary)'>
                      Prêmios 4
                      </Heading>
                    </Center>
                    <Center>
                      <Divider w='full' marginTop={'3%'} h='0.1em' bg='gray.400' orientation='horizontal' />
                    </Center>
                    <Text marginTop='15px' fontWeight={'400'} color='#616161'>
                    Este prêmio reconhece um fulano que teve uma nova ideia ou processo que teve um impacto positivo na empresa
                     </Text>
                  </Box>

                  <motion.div
                    whileHover={{ rotateX: 360 }}
                    transition={{ duration: 1 }}
                    style={{ display: 'inline-block' }}
                  >
                    <IconButton
                      marginTop='0px'
                      marginLeft='30px'
                      bg='transparent'
                      _hover={{ bg: 'transparent' }}
                      aria-label='Search database'
                      icon={<BsArrowRight color="var(--primary)" size='40px' />}
                    />
                  </motion.div>
                </Box>
              </motion.div>
            </WrapItem>

          </Wrap>

        </Box>



      </Center>
      <Box
        w='full'
        justifyContent={'flex-start'}
        backgroundColor='white'
        paddingBottom='5%'
        paddingTop='10%'
      >
        <Center w='full' >
          <Box margin='0px 0px  0px 5%' w='95%'>
            <PreTitle colorTitle={'var(--secondary)'} base='0%' md='0%' lg='0%' text='NOSSOS TESTEMUNHO' title='O Que Nossos Clientes Dizem' />
             </Box>
        </Center >
        <Divider marginTop={'3%'} h='0.08em' bg='gray.300' orientation='horizontal' />
        

        <Center w='full' marginTop='5%'  >
          <SliderTestemonials />
        </Center>
      </Box>
    </>
  )
}
export const getStaticProps: GetStaticProps = async () => {

  return {
    props: {
    },
    revalidate: 60 * 30 // a CADA 2 MIN
  }
}